osx_image: xcode8.0
language: objective-c
branches:
  only:
    - develop
    - master
notification:
  email: false
before_install:
  - gem install bundler
  - bundle install && brew bundle
script:
  - bundle exec fastlane tests
